-- =========================================================================
-- NEXORA COMMERCE - DATABASE SCHEMA (CONSOLIDATED)
-- Version: 1.0
-- Purpose: Complete initialization with all business logic & security
-- =========================================================================

-- Enable vector and UUID extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- Hàm phục vụ trigger tự động cập nhật thời gian sửa đổi cho PostgreSQL
CREATE OR REPLACE FUNCTION update_order_last_modified()
RETURNS TRIGGER AS $$
BEGIN
    NEW.last_modified_date = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================================
-- PHÂN HỆ 1: NGƯỜI DÙNG & BẢO MẬT (6 TABLES)
-- =========================================================================

-- 1. Table: users
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100),
    email VARCHAR(100) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CONSTRAINT chk_users_status CHECK (status IN ('ACTIVE','BANNED','INACTIVE')),
    avatar_url VARCHAR(255),
    phone_number VARCHAR(20) UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 2. Table: roles
CREATE TABLE IF NOT EXISTS roles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

-- 3. Table: users_roles (Junction table)
CREATE TABLE IF NOT EXISTS users_roles (
    user_id UUID NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_users_roles_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE
);

-- 4. Table: user_addresses
CREATE TABLE IF NOT EXISTS user_addresses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    receiver_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    address_line VARCHAR(255) NOT NULL,
    is_default BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_user_addresses_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 5. Table: refresh_tokens
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 6. Table: verification_tokens
CREATE TABLE IF NOT EXISTS verification_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    type VARCHAR(50) NOT NULL, -- 'EMAIL_VERIFICATION' or 'PASSWORD_RESET'
    expiry_date TIMESTAMP NOT NULL,
    CONSTRAINT fk_verification_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- =========================================================================
-- PHÂN HỆ 2: DANH MỤC & BIẾN THỂ SẢN PHẨM (8 TABLES)
-- =========================================================================

-- 7. Table: categories
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    parent_id BIGINT,
    image_url VARCHAR(255),
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL
);

-- 8. Table: brands
CREATE TABLE IF NOT EXISTS brands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(100) NOT NULL UNIQUE,
    image_url VARCHAR(255)
);

-- 9. Table: products
CREATE TABLE IF NOT EXISTS products (
    id VARCHAR(50) PRIMARY KEY, -- Custom product ID (e.g. 'P001')
    name VARCHAR(255) NOT NULL,
    description TEXT,
    category_id BIGINT,
    brand_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CONSTRAINT chk_products_status CHECK (status IN ('ACTIVE','INACTIVE')),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL,
    CONSTRAINT fk_products_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE SET NULL
);

-- 10. Table: product_attributes
CREATE TABLE IF NOT EXISTS product_attributes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

-- 11. Table: product_attribute_values
CREATE TABLE IF NOT EXISTS product_attribute_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attribute_id BIGINT NOT NULL,
    value VARCHAR(100) NOT NULL,
    CONSTRAINT fk_attribute_values_attribute FOREIGN KEY (attribute_id) REFERENCES product_attributes(id) ON DELETE CASCADE,
    CONSTRAINT uq_attribute_value UNIQUE (attribute_id, value)
);

-- 12. Table: product_variants
CREATE TABLE IF NOT EXISTS product_variants (
    sku VARCHAR(50) PRIMARY KEY, -- Custom SKU (e.g. 'IP15-BLK-128')
    product_id VARCHAR(50) NOT NULL,
    price BIGINT NOT NULL CONSTRAINT chk_variant_price CHECK (price >= 0),
    original_price BIGINT CONSTRAINT chk_variant_original_price CHECK (original_price IS NULL OR original_price >= 0),
    quantity INTEGER NOT NULL DEFAULT 0 CONSTRAINT chk_variant_qty CHECK (quantity >= 0),
    reserved_quantity INTEGER NOT NULL DEFAULT 0 CONSTRAINT chk_variant_reserved CHECK (reserved_quantity >= 0),
    sold_quantity INTEGER NOT NULL DEFAULT 0 CONSTRAINT chk_variant_sold CHECK (sold_quantity >= 0),
    weight INTEGER DEFAULT 0, -- Trọng lượng (gram) để tính phí ship
    length INTEGER DEFAULT 0, -- Kích thước (cm)
    width INTEGER DEFAULT 0,
    height INTEGER DEFAULT 0,
    embedding vector(768), -- Embedding vector for Semantic Search using Gemini text-embedding-004
    CONSTRAINT fk_variants_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT chk_price_logic CHECK (original_price IS NULL OR original_price >= price)
);

-- 13. Table: variant_attribute_values (Junction table)
CREATE TABLE IF NOT EXISTS variant_attribute_values (
    sku VARCHAR(50) NOT NULL,
    value_id BIGINT NOT NULL,
    PRIMARY KEY (sku, value_id),
    CONSTRAINT fk_variant_attr_variant FOREIGN KEY (sku) REFERENCES product_variants(sku) ON DELETE CASCADE,
    CONSTRAINT fk_variant_attr_value FOREIGN KEY (value_id) REFERENCES product_attribute_values(id) ON DELETE CASCADE
);

-- 14. Table: product_images
CREATE TABLE IF NOT EXISTS product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id VARCHAR(50) NOT NULL,
    sku VARCHAR(50), -- Can reference a specific variant
    image_url VARCHAR(255) NOT NULL,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_images_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT fk_images_variant FOREIGN KEY (sku) REFERENCES product_variants(sku) ON DELETE CASCADE
);

-- =========================================================================
-- PHÂN HỆ 3: GIỎ HÀNG & YÊU THÍCH (2 TABLES)
-- =========================================================================

-- 15. Table: cart_items
CREATE TABLE IF NOT EXISTS cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    variant_sku VARCHAR(50) NOT NULL,
    quantity INTEGER NOT NULL CONSTRAINT chk_cart_quantity CHECK (quantity > 0),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_items_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_cart_items_variant FOREIGN KEY (variant_sku) REFERENCES product_variants(sku) ON DELETE CASCADE,
    CONSTRAINT uq_user_variant UNIQUE (user_id, variant_sku)
);

-- 16. Table: wishlists
CREATE TABLE IF NOT EXISTS wishlists (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    product_id VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_wishlists_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_wishlists_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
    CONSTRAINT uq_user_product UNIQUE (user_id, product_id)
);

-- =========================================================================
-- PHÂN HỆ 4: ĐƠN HÀNG, LỊCH SỬ & KHUYẾN MÃI (5 TABLES)
-- =========================================================================

-- 17. Table: coupons
CREATE TABLE IF NOT EXISTS coupons (
    code VARCHAR(50) PRIMARY KEY,
    discount_percent INTEGER CONSTRAINT chk_coupon_percent CHECK (discount_percent IS NULL OR (discount_percent > 0 AND discount_percent <= 100)),
    discount_type VARCHAR(20) NOT NULL DEFAULT 'PERCENTAGE', -- 'PERCENTAGE' hoặc 'FIXED_AMOUNT'
    active BOOLEAN NOT NULL DEFAULT TRUE,
    minimum_order_amount BIGINT NOT NULL DEFAULT 0 CONSTRAINT chk_coupon_min_amount CHECK (minimum_order_amount >= 0),
    max_discount_amount BIGINT CONSTRAINT chk_coupon_max_discount CHECK (max_discount_amount IS NULL OR max_discount_amount >= 0),
    usage_limit INTEGER, -- Giới hạn tổng số lượt nhập
    used_count INTEGER NOT NULL DEFAULT 0 CONSTRAINT chk_coupon_used CHECK (used_count >= 0),
    start_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expiry_date TIMESTAMP,
    CONSTRAINT chk_coupon_usage_limit CHECK (usage_limit IS NULL OR used_count <= usage_limit)
);

-- 18. Table: orders
CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(50) PRIMARY KEY, -- Custom Order ID (e.g. 'ORD-1001')
    user_id UUID NOT NULL,
    total_price BIGINT NOT NULL CONSTRAINT chk_order_total CHECK (total_price >= 0),
    shipping_fee BIGINT NOT NULL DEFAULT 0 CONSTRAINT chk_order_shipping CHECK (shipping_fee >= 0),
    discount_amount BIGINT NOT NULL DEFAULT 0 CONSTRAINT chk_order_discount CHECK (discount_amount >= 0),
    coupon_code VARCHAR(50),
    shipping_address VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    status VARCHAR(50) NOT NULL, -- e.g. 'PENDING', 'PROCESSING', 'SHIPPING', 'DELIVERED', 'CANCELLED'
    payment_status VARCHAR(50) NOT NULL DEFAULT 'UNPAID', -- 'UNPAID', 'PAID', 'REFUNDED'
    customer_note TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_modified_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE RESTRICT,
    CONSTRAINT fk_orders_coupon FOREIGN KEY (coupon_code) REFERENCES coupons(code) ON DELETE SET NULL
);

-- 19. Table: order_items
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(50) NOT NULL,
    variant_sku VARCHAR(50) NOT NULL,
    product_name VARCHAR(255) NOT NULL, -- Snapshot of product name at checkout
    variant_name VARCHAR(255), -- Snapshot of variant info at checkout
    quantity INTEGER NOT NULL CONSTRAINT chk_order_item_qty CHECK (quantity > 0),
    price BIGINT NOT NULL CONSTRAINT chk_order_item_price CHECK (price >= 0), -- Price snapshot at checkout
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_variant FOREIGN KEY (variant_sku) REFERENCES product_variants(sku) ON DELETE RESTRICT,
    CONSTRAINT uq_order_items UNIQUE (order_id, variant_sku)
);

-- 20. Table: order_status_history (Audit Log)
CREATE TABLE IF NOT EXISTS order_status_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    changed_by VARCHAR(100) NOT NULL, -- Username or 'SYSTEM'
    reason VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_history_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

-- 21. Table: payment_transactions
CREATE TABLE IF NOT EXISTS payment_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(50) NOT NULL,
    payment_method VARCHAR(50) NOT NULL, -- 'COD', 'VNPAY', 'MOMO'
    amount BIGINT NOT NULL CONSTRAINT chk_payment_amount CHECK (amount >= 0),
    provider_transaction_id VARCHAR(255), -- Reference ID from payment provider
    status VARCHAR(50) NOT NULL, -- 'PENDING', 'SUCCESS', 'FAILED'
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_payment_trans_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

-- =========================================================================
-- PHÂN HỆ 5: ĐÁNH GIÁ & TƯƠNG TÁC AI (3 TABLES)
-- =========================================================================

-- 22. Table: product_reviews
CREATE TABLE IF NOT EXISTS product_reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    variant_sku VARCHAR(50) NOT NULL,
    order_id VARCHAR(50), -- Linked to verified purchase
    rating INTEGER NOT NULL CONSTRAINT chk_review_rating CHECK (rating >= 1 AND rating <= 5),
    comment TEXT,
    parent_id BIGINT, -- Self reference for Admin replies
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reviews_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_variant FOREIGN KEY (variant_sku) REFERENCES product_variants(sku) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE SET NULL,
    CONSTRAINT fk_reviews_parent FOREIGN KEY (parent_id) REFERENCES product_reviews(id) ON DELETE CASCADE
);

-- 23. Table: review_images
CREATE TABLE IF NOT EXISTS review_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    review_id BIGINT NOT NULL,
    image_url VARCHAR(255) NOT NULL,
    CONSTRAINT fk_review_images_review FOREIGN KEY (review_id) REFERENCES product_reviews(id) ON DELETE CASCADE
);

-- 24. Table: ai_chat_messages (AI Conversation Log)
CREATE TABLE IF NOT EXISTS ai_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID, -- Can be null for guest session
    session_id VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL, -- 'USER' or 'AI'
    content TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ai_messages_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

-- =========================================================================
-- TRIGGERS & INDEXES OPTIMIZATION
-- =========================================================================

-- Tự động hóa cập nhật thời gian sửa đổi cho bảng orders
CREATE OR REPLACE TRIGGER tg_orders_last_modified
    BEFORE UPDATE ON orders
    FOR EACH ROW
    EXECUTE FUNCTION update_order_last_modified();

-- Tạo các chỉ mục tối ưu hiệu năng tìm kiếm nâng cao
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand ON products(brand_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);
CREATE INDEX IF NOT EXISTS idx_variants_product ON product_variants(product_id);
CREATE INDEX IF NOT EXISTS idx_variants_price ON product_variants(price);
CREATE INDEX IF NOT EXISTS idx_cart_items_user ON cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders(payment_status);
CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_reviews_variant ON product_reviews(variant_sku);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON product_reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_ai_chat_session ON ai_chat_messages(session_id);
CREATE INDEX IF NOT EXISTS idx_coupons_active_expiry ON coupons(active, expiry_date);
CREATE INDEX IF NOT EXISTS idx_coupons_code ON coupons(code);
